name: Deploy Frontend (Production)

on:
  push:
    branches:
      - production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.18.1"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build-dev
        env:
          CI: false

      - name: Verify build output
        run: ls -R dist

      - name: Install sshpass
        run: sudo apt-get install sshpass -y

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image (Production)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: yminds/employability-frontend-p:latest

      - name: Deploy Backend on Ubuntu VM (Production)
        env:
          SSHPASS: ${{ secrets.PROD_AZURE_VM_PASSWORD }}
        run: |
          sshpass -e ssh -o StrictHostKeyChecking=no ${{ secrets.PROD_AZURE_VM_USERNAME }}@${{ secrets.PROD_AZURE_VM_IP }} << EOF
            cd ~/employability.ai
            sudo docker login -u yminds -p ${{ secrets.DOCKER_HUB_PASSWORD }}
            sudo docker compose down
            sudo docker compose up -d
            sudo docker system prune -f
          EOF