name: Deploy dev

on:
  push:
    branches:
      - dev  # Trigger workflow on pushes to the 'dev' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Identify changed and deleted files
        id: files
        run: |
          changed_files=$(git diff --name-only --diff-filter=d ${{github.event.before}} ${{github.sha}} | xargs)
          deleted_files=$(git diff --name-only --diff-filter=D ${{github.event.before}} ${{github.sha}} | xargs)
          
          echo "changed_files=$changed_files" >> $GITHUB_ENV
          echo "deleted_files=$deleted_files" >> $GITHUB_ENV

          if [[ -z "$changed_files" && -z "$deleted_files" ]]; then
            echo "No files changed or deleted. Exiting..."
            exit 0
          fi

      - name: Compress changed files
        if: env.changed_files != ''
        run: |
          zip -r changed_files.zip $changed_files
          echo "ZIP_EXISTS=true" >> $GITHUB_ENV

      - name: Set up SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.AZURE_SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

      - name: Copy resources to server
        if: env.changed_files != '' || env.deleted_files != ''
        run: |
          echo "Transferring changed files and deleted files list to server..."

          if [[ $ZIP_EXISTS == "true" ]]; then
            scp -i private_key.pem -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no changed_files.zip azure-user@${{ secrets.AZURE_VM_IP }}:E:/Inetpub/vhosts/employability.ai/httpdocs/test/changed_files.zip
          fi

          if [[ $deleted_files != '' ]]; then
            echo $deleted_files > deleted_files.txt
            scp -i private_key.pem -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no deleted_files.txt azure-user@${{ secrets.AZURE_VM_IP }}:E:/Inetpub/vhosts/employability.ai/httpdocs/test/deleted_files.txt
          fi

      - name: Update server (unzip and delete files)
        if: env.changed_files != '' || env.deleted_files != ''
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: azure-user
          key: ${{ secrets.AZURE_SSH_PRIVATE_KEY }}
          script: |
            powershell.exe -Command "
              # Handle changed files
              if (Test-Path -Path 'E:\\Inetpub\\vhosts\\employability.ai\\httpdocs\\test\\changed_files.zip') {
                Expand-Archive -Path 'E:\\Inetpub\\vhosts\\employability.ai\\httpdocs\\test\\changed_files.zip' -DestinationPath 'E:\\Inetpub\\vhosts\\employability.ai\\httpdocs\\test' -Force;
                Remove-Item -Path 'E:\\Inetpub\\vhosts\\employability.ai\\httpdocs\\test\\changed_files.zip' -Force;
              }

              # Handle deleted files
              if (Test-Path -Path 'E:\\Inetpub\\vhosts\\employability.ai\\httpdocs\\test\\deleted_files.txt') {
                $files = Get-Content -Path 'E:\\Inetpub\\vhosts\\employability.ai\\httpdocs\\test\\deleted_files.txt';
                foreach ($file in $files) {
                  Remove-Item -Path ('E:\\Inetpub\\vhosts\\employability.ai\\httpdocs\\test\\' + $file) -Force;
                }
                Remove-Item -Path 'E:\\Inetpub\\vhosts\\employability.ai\\httpdocs\\test\\deleted_files.txt' -Force;
              }
            "

      - name: Clean up local temporary files
        run: |
          echo "Cleaning up local temporary files..."
          rm -f changed_files.zip deleted_files.txt private_key.pem
