name: Deploy Frontend

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.18.1'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build-dev
        env:
          CI: false

      - name: Verify build output
        run: ls -R dist

      - name: Install sshpass
        run: sudo apt-get install sshpass -y

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with: 
          context: .
          file: ./Dockerfile
          push: true
          tags: yminds/employability-frontend:latest

      - name: Deploy Backend on Ubuntu VM
        env:
          SSHPASS: ${{ secrets.AZURE_VM_PASSWORD_NEW }}
        run: |
          sshpass -e ssh -o StrictHostKeyChecking=no ${{ secrets.AZURE_VM_USERNAME_NEW }}@${{ secrets.AZURE_VM_IP_NEW }} << EOF
            cd ~/employability.ai
            sudo docker login -u yminds -p ${{ secrets.DOCKER_HUB_PASSWORD }}
            sudo docker compose down
            sudo docker compose up -d
            sudo docker system prune -f
          EOF         
   