name: Deploy Main Branch

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Identify changed and deleted files
        id: files
        run: |
          echo "changed_files=$(git diff --name-only --diff-filter=d ${{github.event.before}} ${{github.sha}} | xargs)" >> $GITHUB_ENV
          echo "deleted_files=$(git diff --name-only --diff-filter=D ${{github.event.before}} ${{github.sha}} | xargs)" >> $GITHUB_ENV

      - name: Compress dir
        if: env.changed_files != ''
        run: |
          zip -r ../changed_files.zip $changed_files
          echo "ZIP_EXISTS=true" >> $GITHUB_ENV

      - name: Install ssh pass
        run: sudo apt-get install sshpass -y

      - name: Copy resources to server
        if: env.changed_files != '' || env.deleted_files != ''
        env:
          SSHPASS: ${{secrets.AZURE_VM_PASSWORD}}
        run: |
          if [[ $ZIP_EXISTS == "true" ]]; then
            sshpass -e scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ../changed_files.zip ${{secrets.AZURE_VM_USERNAME}}@${{ secrets.AZURE_VM_IP }}:E:/Inetpub/vhosts/employability.ai/changed_files.zip
          fi

      - name: Update server (unzip and delete files)
        if: env.changed_files != '' || env.deleted_files != ''
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{secrets.AZURE_VM_IP}}
          username: ${{secrets.AZURE_VM_USERNAME}}
          password: ${{secrets.AZURE_VM_PASSWORD}}
          script: |
            powershell.exe -Command "
              if (Test-Path -Path 'E:\\Inetpub\\vhosts\\employability.ai\\changed_files.zip') {
                Expand-Archive -Path 'E:\\Inetpub\\vhosts\\employability.ai\\changed_files.zip' -DestinationPath 'E:\\Inetpub\\vhosts\\employability.ai' -Force;
                Remove-Item -Path 'E:\\Inetpub\\vhosts\\employability.ai\\changed_files.zip' -Force;
              }
            "
